version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5434:5434'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    command: -p 5434

volumes:
  postgres:
